# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Coding Abap
tagline:             'Personal Abap blog'
description:         'Personal Abap blog'
url:                 http://coding-abap.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              diesire
  url:               https://github.com/diesire
  email:             diesire@gmail.com

# Custom vars
version:             1.0.0
